openapi: 3.0.1
info:
    title: All Things E-Store
    version: 1.0.0
    description: An online store where you can buy ALMOST anything you can think of!
paths:
    /api/v1/categories:
        summary: Category Management
        description: >-
            Endpoints related to retrieving and managing all categories
            withing the store's database.
        get:
            summary: Search and filter categories.
            description: Retrieves categories from the store's database based on search criteria
            operationId: search_categories
            responses:
                "200":
                    description: The list of categories was successfully retrieved.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/Category"
                "500":
                    description: Server error
            tags:
                - Category
        post:
            summary: Add a category
            description: Adds a new category to the database
            operationId: add_category
            security:
                - bearerAuth: []
            requestBody:
                description: A new category object
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Category"
            responses:
                "200":
                    description: Category created
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Category"
                "500":
                    description: Server error
            tags:
                - Category
    /api/v1/categories/{id}:
        summary: Retrieve a single category by ID
        description: Retrieves a single category from the database by given ID
        get:
            summary: Get a category
            description: This operation retrieves an object with the matching id
            operationId: get_category_id
            responses:
                "200":
                    description: The category was successfully retrieved.
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Category"
            parameters:
                - name: id
                  in: path
                  description: The id of the category.
                  required: true
                  schema:
                      type: string
            tags:
                - Category
        put:
            summary: Update a Category.
            description: This operation updates an object with the matching id.
            security:
                - bearerAuth: []
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Category"
            responses:
                "200":
                    description: The category was successfully updated.
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Product"
                "404":
                    description: No category found
            tags:
                - Category
        delete:
            summary: Delete a category.
            description: This operation deletes an object with the matching id.
            operationId: delete_category_id
            security:
                - bearerAuth: []
            responses:
                "200":
                    description: The category was deleted successfully
                "403":
                    description: User does not have elevated role to complete this operation.
                "500":
                    description: Server error
            parameters:
                - name: id
                  in: path
                  schema:
                      type: string
                  required: true
            tags:
                - Category
    /api/v1/products:
        summary: Product Management
        description: >-
            Endpoints related to retrieving and managing all products within the
            store's database.
        get:
            summary: Search and filter products
            description: Retrieves products from the store's database based on search criteria
            operationId: search_products
            parameters:
                - in: query
                  name: category
                  schema:
                      type: string
                  description: Filter products by category
                - in: query
                  name: name
                  schema:
                      type: string
                  description: Search products by name
                - in: query
                  name: min_price
                  schema:
                      type: number
                      format: float
                  description: Filter products by minimum price
                - in: query
                  name: max_price
                  schema:
                      type: number
                      format: float
                  description: Filter products by maximum price
                - in: query
                  name: page
                  schema:
                      type: number
                      format: integer
                  description: The page number to retrieve
                - in: query
                  name: limit
                  schema:
                      type: number
                      format: float
                  description: The number of products per page
            responses:
                "200":
                    description: The list of products was successfully retrieved
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/Product"
                "500":
                    description: Server error
            tags:
                - Products
        post:
            summary: Add a product
            description: Adds a new product to the database
            operationId: add_product
            security:
                - bearerAuth: []
            requestBody:
                description: A new product object
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Product"
            responses:
                default:
                    description: Default error sample response
            tags:
                - Products
    /api/v1/products/{id}:
        summary: Retrieve a single product by ID
        description: Retrieves a single product from the database by given ID
        get:
            summary: Get a product
            description: This operation retrieves an object with the matching id
            operationId: get_product_id
            responses:
                "200":
                    description: The product was successfully retrieved.
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Product"
            parameters:
                - name: id
                  in: path
                  description: The id of the product.
                  required: true
                  schema:
                      type: string
            tags:
                - Products
        put:
            summary: Update a product.
            description: This operation updates an object with the matching id
            operationId: update_product_id
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Product"
            responses:
                "200":
                    description: The product was successfully retrieved.
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Product"
            parameters:
                - name: id
                  in: path
                  description: The id of the product.
                  required: true
                  schema:
                      type: string
            tags:
                - Products
        delete:
            summary: Delete a product.
            description: This product deletes an object with the matching id.
            operationId: delete_product_id
            security:
                - bearerAuth: []
            responses:
                "200":
                    description: The product was deleted successfully
                "403":
                    description: User does not have elevated role to complete this operation.
                "500":
                    description: Server error
            parameters:
                - name: id
                  in: path
                  schema:
                      type: string
                  required: true
            tags:
                - Products
    /api/v1/user:
        summary: Endpoints for all user related requests

        post:
            summary: Add a user.
            description: This operation creates a new user.
            operationId: add_user
            security:
                - bearerAuth: []
            requestBody:
                description: A new user object
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/User"
            responses:
                "200":
                    description: The user has been created
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/User"
            tags:
                - User
    /api/v1/user/{id}:
        summary: Allow the user to login.
        description: Endpoints relating to all user info.
        get:
            summary: Get a user
            description: This operation retrieves an object with the matching id
            operationId: get_user
            parameters:
                - in: path
                  name: id
                  schema:
                      type: string
                  description: The user's id.
                  required: true
            security:
                - bearerAuth: []
            responses:
                "200":
                    description: The user was successfully retrieved.
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/User"
            tags:
                - User
        delete:
            summary: Delete a user
            security:
                - bearerAuth: []
            parameters:
                - in: path
                  name: id
                  schema:
                    type: string
                  required: true
                  description: The user's id
            responses:
                "200":
                    description: The user has been deleted
            tags:
                - User
        put:
            summary: Update a user
            description: This operation updates the user at the provided with the object within the request body.
            security:
                - bearerAuth: []
            parameters:
                - in: path
                  name: id
                  schema:
                    type: string
                  required: true
                  description: The user's id
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#components/schemas/User"
            responses:
                "200":
                    description: The user has been updated.
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/User"
            tags:
                - User
    /api/v1/orders:
        description: Endpoints for retrieving orders.
        get:
            summary: Get all orders
            description: This operation retrieves all orders with the matching id
            operationId: get_orders
            parameters:
                - 
                    in: query
                    name: limit
                    schema:
                        type: integer
                        minimum: 1
                        maximum: 100
                        default: 25
                    description: The number of orders to return
                    example: 25
            security:
                - bearerAuth: []
            responses:
                "200":
                    description: The user was successfully retrieved.
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Order"
            tags:
                - Orders
        post:
            tags:
                - Orders
    /api/v1/orders/{id}:
        put:
            tags:
                - Orders
    /api/v1/heros:
        description: Endpoints relating to site heros (banners)
        get:
            tags:
                - Heros
        post:
            tags:
                - Heros
    /api/v1/heros/{id}:
        put:
            tags:
                - Heros
        delete:
            tags:
                - Heros
    /api/v1/roles/{id}:
        description: Endpoints relating to user roles.
        get:
            tags:
                - Roles
        put:
            tags:
                - Roles
    /api/v1/discounts:
        description: Endpoints relating to product discounts
        get:
            tags:
                - Discounts
        post:
            tags:
                - Discounts
    /api/v1/discounts/{id}:
        put:
            tags:
                - Discounts
        delete:
            tags:
                - Discounts
    /api/v1/carts:
        description: Endpoints relating to user carts.
        post:
            tags:
                - Carts
    /api/v1/carts{id}:
        put:
            tags:
                - Carts
        get:
            tags:
                - Carts
        delete:
            tags:
                - Carts
    /api/auth/login:
        post:
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    accessToken:
                                        type: string
            tags:
                - Auth
    /api/auth/register:
        post:
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    accessToken:
                                        type: string
            tags:
                - Auth
    /api/auth/logout:
        post:
            tags:
                - Auth

components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT

    schemas:
        Category:
            type: object
            properties:
                id:
                    type: integer
                    description: Auto-incrementing primary key
                name:
                    type: string
                    description: The name of the category
                description:
                    type: string
                    description: The description for the category
            required:
                - id
                - name
                - description
        User:
            type: object
            properties:
                email:
                    type: string
                    description: The email for the user (PK)
                username:
                    type: string
                    maxLength: 50
                    description: The user's username.
                name:
                    type: string
                    maxLength: 254
                    description: The user's name
                streetName: 
                    type: string
                    maxLength: 75
                    description: The name of the street the user ships to.
                streetNumber:
                    type: string
                city:
                    type: string
                state:
                    type: string
                zipCode:
                    type: string
                phoneNumber:
                    type: string
        Order:
            type: object
            properties:
                id:
                    type: integer
                    description: Auto-incrementing primary key
                userId:
                    type: string
                    description: The user's id
                products:
                    type: array
                    items: 
                        type: string
                    description: The products in the order
                purchaseDate:
                    type: string
                    format: date
                    description: The date the order was purchased
                status:
                    type: string
                    description: The status of the order
                discounts:
                    type: array
                    items:
                        type: string
                    description: The discounts applied to the order
                orderTotal:
                    type: number
                    format: float
                    description: The total cost of the order

                
        Product:
            type: object
            properties:
                id:
                    type: integer
                    description: Auto-incrementing primary key
                barcode:
                    type: string
                    maxLength: 20
                    description: The barcode of the product
                    nullable: true
                name:
                    type: string
                    maxLength: 50
                    description: The name of the product
                description:
                    type: string
                    maxLength: 254
                    description: A detailed description of the product
                    nullable: true
                price:
                    type: number
                    format: float
                    description: The price of the product, must be greater than 0
                quantity:
                    type: integer
                    description: The quantity of the product in stock, must be greater than 0
            required:
                - id
                - name
                - price
                - quantity
